---
- name: create database user
  delegate_to: "{{ artifactory_db_delegate_to }}"
  sudo_user: postgres
  postgresql_user: >
    name={{ artifactory_db_user }}
    password="{{ artifactory_db_pass }}"
  tags: accounts

- name: create database
  delegate_to: "{{ artifactory_db_delegate_to }}"
  sudo_user: postgres
  postgresql_db: >
    name={{ artifactory_db_name }}
    owner={{ artifactory_db_user }}
